//
// Created by Anzhalika Dziarkach on 03.04.2022.
//

#ifndef PCH_H
#define PCH_H

#define LED_PIN 15
#define VIBRO_PIN 21
#define SOUND_PIN 12
#define MICROPHONE_PIN 14

#define MOVEMENT_JOYSTICK_X 32
#define MOVEMENT_JOYSTICK_Y 35
#define MOVEMENT_JOYSTICK_Z 19

#define CAMERA_JOYSTICK_X 34
#define CAMERA_JOYSTICK_Y 33
#define CAMERA_JOYSTICK_Z 14

#define NEXT_PAGE_BUTTON 22
#define NEXT_SETTING_BUTTON 26
#define CHANGE_SETTING_BUTTON 27
#define PREVIOUS_SETTING_BUTTON 25


#endif //PCH_H
